import { build, context } from 'esbuild';
import { PACKAGE_ASSETS } from './package-assets.mjs';
import { copyFile, mkdir, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const output = path.join(root, 'dist');
await mkdir(output, { recursive: true });
const options = {
  absWorkingDir: root,
  entryPoints: ['src/main.ts'],
  outfile: 'dist/main.js',
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  target: 'es2022',
  external: ['obsidian'],
  loader: { '.css': 'text' },
  minify: false,
  sourcemap: false,
  metafile: true,
  banner: { js: '// Generated from src/main.ts. Do not edit this file.' },
  plugins: [
    {
      name: 'package-assets',
      setup(builder) {
        builder.onLoad({ filter: /[\\/]src[\\/]main\.ts$/ }, async (args) => ({
          contents: await readFile(args.path, 'utf8'),
          loader: 'ts',
          resolveDir: path.dirname(args.path),
          watchFiles: PACKAGE_ASSETS.map((name) => path.join(root, name)),
        }));
        builder.onEnd(async (result) => {
          if (result.errors.length) return;
          for (const name of PACKAGE_ASSETS) {
            await mkdir(path.dirname(path.join(output, name)), { recursive: true });
            await copyFile(path.join(root, name), path.join(output, name));
          }
          await mkdir(path.join(root, '.build'), { recursive: true });
          await writeFile(
            path.join(root, '.build/metafile.json'),
            JSON.stringify(result.metafile, null, 2),
          );
        });
      },
    },
  ],
};
if (process.argv.includes('--watch')) {
  const watcher = await context(options);
  await watcher.watch();
  console.log(
    'Watching source modules and package assets. Reload the Obsidian plugin after rebuilding.',
  );
  for (const signal of ['SIGINT', 'SIGTERM'])
    process.once(signal, async () => {
      await watcher.dispose();
      process.exit(0);
    });
} else {
  await build(options);
  console.log('Built dist/main.js, plugin assets and localized guides with example images.');
}
